# vim:ft=kitty

## name: Violet Void
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/violet-void.nvim/raw/main/extras/kitty/violet_void.conf


background #0f0f0f
foreground #e7e7e7
selection_background #191919
selection_foreground #e7e7e7
url_color #00fff9
cursor #e7e7e7
cursor_text_color #0f0f0f

# Tabs
active_tab_background #29adff
active_tab_foreground #181818
inactive_tab_background #222222
inactive_tab_foreground #383838
#tab_bar_background #181818

# Windows
active_border_color #29adff
inactive_border_color #222222

# normal
color0 #181818
color1 #ff004b
color2 #42ff97
color3 #7c60d1
color4 #29adff
color5 #fd007f
color6 #00fff9
color7 #e7e7e7

# bright
color8  #333333
color9  #ff1a67
color10 #42ffad
color11 #d0a9e5
color12 #70c8ff
color13 #fd0098
color14 #b6e3ff
color15 #e7e7e7

# extended colors
color16 #fa9f80
color17 #ff004b
